name: Formatter
on: workflow_dispatch
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Installing Libraries
        run: haxelib --quiet install formatter

      - name: Formatting
        run: haxelib run formatter -s sourceJon --check

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Source-Files
          path: sourceJon
          if-no-files-found: error
